# Base image
FROM pytorch/pytorch:2.2.2-cuda12.1-cudnn8-runtime

# Install Python packages
RUN pip install --no-cache-dir pandas numpy python-chess

# Set default workdir (Already set in base image)
# WORKDIR /workspace
